## Import Necesaary Libraries

In [6]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

## Import Datasets

In [24]:
breast_cancer_data=load_breast_cancer()
breast_cancer_data_df=pd.DataFrame(breast_cancer_data.data,columns=breast_cancer_data.feature_names)
breast_cancer_data_df["Target"]=breast_cancer_data.target

In [25]:
breast_cancer_data_df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [18]:
breast_cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

## 3.Data Understandings

In [26]:
breast_cancer_data_df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [27]:
breast_cancer_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

## 4.Data Preperation

In [31]:
X=breast_cancer_data_df.drop("Target",axis=1)

In [36]:
std_scaler=StandardScaler()
scaled_x=pd.DataFrame(std_scaler.fit_transform(X))
scaled_x

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,-0.312589,-0.931027,...,1.901185,0.117700,1.752563,2.015301,0.378365,-0.273318,0.664512,1.629151,-1.360158,-0.709091
565,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,-0.217664,-1.058611,...,1.536720,2.047399,1.421940,1.494959,-0.691230,-0.394820,0.236573,0.733827,-0.531855,-0.973978
566,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,-0.809117,-0.895587,...,0.561361,1.374854,0.579001,0.427906,-0.809587,0.350735,0.326767,0.414069,-1.104549,-0.318409
567,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,2.137194,1.043695,...,1.961239,2.237926,2.303601,1.653171,1.430427,3.904848,3.197605,2.289985,1.919083,2.219635
568,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,-0.820070,-0.561032,...,-1.410893,0.764190,-1.432735,-1.075813,-1.859019,-1.207552,-1.305831,-1.745063,-0.048138,-0.751207

In [40]:
y=breast_cancer_data_df.Target
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: Target, Length: 569, dtype: int64

## 5.Model Building

In [42]:
from sklearn.ensemble import GradientBoostingClassifier

In [45]:
gradient_boosting_classifier=GradientBoostingClassifier(n_estimators=50,max_depth=3)

In [47]:
x_train,x_test,y_train,y_test=train_test_split(scaled_x,y,test_size=0.20,random_state=123,shuffle=True,stratify=y)

## 6. Model Training

In [50]:
gradient_boosting_classifier.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=50)

In [75]:
from datetime import datetime

In [76]:
start_time=datetime.now()
gradient_boosting_classifier.fit(x_train,y_train)
end_time=datetime.now()

print("Time taken to train the algorithm:",end_time-start_time)

Time taken to train the algorithm: 0:00:00.980889

## 7.Model Testing || 8.Model EValuation

### Training Data

In [61]:
y_pred_train=gradient_boosting_classifier.predict(x_train)
print("Confusion_Matrix: \n",confusion_matrix(y_pred_train,y_train))
print("Accuracy_Score:",accuracy_score(y_pred_train,y_train))
print("Precision_Score:",precision_score(y_pred_train,y_train))
print("Recall_Score:",recall_score(y_pred_train,y_train))

Confusion_Matrix:
 [[170   0]
 [  0 285]]
Accuracy_Score: 1.0
Precision_Score: 1.0
Recall_Score: 1.0

### Test Data

In [62]:
y_pred_test=gradient_boosting_classifier.predict(x_test)
print("Confusion_Matrix: \n",confusion_matrix(y_pred_test,y_test))
print("Accuracy_Score:",accuracy_score(y_pred_test,y_test))
print("Precision_Score:",precision_score(y_pred_test,y_test))
print("Recall_Score:",recall_score(y_pred_test,y_test))

Confusion_Matrix:
 [[40  3]
 [ 2 69]]
Accuracy_Score: 0.956140350877193
Precision_Score: 0.9583333333333334
Recall_Score: 0.971830985915493

## Extreme Gradient Boosting Machines

In [63]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in C:\Users\Smile\AppData\Roaming\Python\Python314\site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in C:\Users\Smile\AppData\Roaming\Python\Python314\site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
    --------------------------------------- 1.0/69.5 MB 9.1 MB/s eta 0:00:08
   - -------------------------------------- 2.9/69.5 MB 9.0 MB/s eta 0:00:08
   -- ------------------------------------- 4.7/69.5 MB 8.7 MB/s eta 0:00:08
   --- ------------------------------------ 6.6/69.5 MB 8.6 MB/s eta 0:00:08
   ---- ----------------------------------- 8.4/69.5 MB 8.5 MB/s eta 0:00:08
   ----- ---------------------------------- 10.0/69.5 MB 8.5 MB/s eta 0:00:08
   ------ --------------------------------- 11.8/69.5 MB 8.5 MB/s eta 0:00:07
   ------- -------------------------------- 13.4/69.5 MB 8.4 MB/s eta 0:00:07
   -------- ------------------------------- 15.2/69.5 MB 8.4 MB/s eta 0:00:07
   --------- ------------------------------ 17.0/69.5 MB 8.4 MB/s eta 0:00:07
   ---------- ----------------------------- 18.6/69.5 MB 8.4 MB/s eta 0:00:07
   ----------- ---------------------------- 20.4/69.5 MB 8.4 MB/s eta 0:00:06
   ------------ --------------------------- 22.3/69.5 MB 8.4 MB/s eta 0:00:06
   ------------- -------------------------- 24.1/69.5 MB 8.4 MB/s eta 0:00:06
   -------------- ------------------------- 25.7/69.5 MB 8.4 MB/s eta 0:00:06
   --------------- ------------------------ 27.5/69.5 MB 8.4 MB/s eta 0:00:05
   ---------------- ----------------------- 29.4/69.5 MB 8.4 MB/s eta 0:00:05
   ----------------- ---------------------- 31.2/69.5 MB 8.4 MB/s eta 0:00:05
   ------------------ --------------------- 32.8/69.5 MB 8.4 MB/s eta 0:00:05
   ------------------- -------------------- 34.6/69.5 MB 8.4 MB/s eta 0:00:05
   -------------------- ------------------- 36.4/69.5 MB 8.4 MB/s eta 0:00:04
   ---------------------- ----------------- 38.3/69.5 MB 8.4 MB/s eta 0:00:04
   ---------------------- ----------------- 39.8/69.5 MB 8.4 MB/s eta 0:00:04
   ----------------------- ---------------- 41.2/69.5 MB 8.4 MB/s eta 0:00:04
   ------------------------ --------------- 43.3/69.5 MB 8.3 MB/s eta 0:00:04
   ------------------------- -------------- 44.8/69.5 MB 8.4 MB/s eta 0:00:03
   -------------------------- ------------- 46.7/69.5 MB 8.4 MB/s eta 0:00:03
   --------------------------- ------------ 48.5/69.5 MB 8.4 MB/s eta 0:00:03
   ---------------------------- ----------- 50.1/69.5 MB 8.4 MB/s eta 0:00:03
   ----------------------------- ---------- 51.9/69.5 MB 8.4 MB/s eta 0:00:03
   ------------------------------ --------- 53.5/69.5 MB 8.4 MB/s eta 0:00:02
   ------------------------------- -------- 55.3/69.5 MB 8.4 MB/s eta 0:00:02
   -------------------------------- ------- 57.1/69.5 MB 8.4 MB/s eta 0:00:02
   --------------------------------- ------ 59.0/69.5 MB 8.4 MB/s eta 0:00:02
   ---------------------------------- ----- 60.6/69.5 MB 8.4 MB/s eta 0:00:02
   ----------------------------------- ---- 62.4/69.5 MB 8.4 MB/s eta 0:00:01
   ------------------------------------ --- 64.2/69.5 MB 8.3 MB/s eta 0:00:01
   ------------------------------------- -- 65.8/69.5 MB 8.4 MB/s eta 0:00:01
   -------------------------------------- - 67.6/69.5 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 7.8 MB/s  0:00:08
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import xgboost as xgb

In [70]:
xgb_classifier=xgb.XGBClassifier( n_estimators=20,max_depth=3, learning_rate =0.01,gamma=1.25)

In [71]:
xgb_classifier.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=1.25, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.01, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=20,
              n_jobs=None, num_parallel_tree=None, ...)

In [77]:
start_time=datetime.now()
xgb_classifier=xgb.XGBClassifier( n_estimators=20,max_depth=3, learning_rate =0.01,gamma=1.25)
end_time=datetime.now()

print("Time taken to train the algorithm:",end_time-start_time)

Time taken to train the algorithm: 0:00:00.000465

## Training Data

In [72]:
y_pred_train=xgb_classifier.predict(x_train)
print("Confusion_Matrix: \n",confusion_matrix(y_pred_train,y_train))
print("Accuracy_Score:",accuracy_score(y_pred_train,y_train))
print("Precision_Score:",precision_score(y_pred_train,y_train))
print("Recall_Score:",recall_score(y_pred_train,y_train))

Confusion_Matrix:
 [[  0   0]
 [170 285]]
Accuracy_Score: 0.6263736263736264
Precision_Score: 1.0
Recall_Score: 0.6263736263736264

## Test Data

In [74]:
y_pred_test=xgb_classifier.predict(x_test)
print("Confusion_Matrix: \n",confusion_matrix(y_pred_test,y_test))
print("Accuracy_Score:",accuracy_score(y_pred_test,y_test))
print("Precision_Score:",precision_score(y_pred_test,y_test))
print("Recall_Score:",recall_score(y_pred_test,y_test))

Confusion_Matrix:
 [[ 0  0]
 [42 72]]
Accuracy_Score: 0.631578947368421
Precision_Score: 1.0
Recall_Score: 0.631578947368421